name: Deploy SAM App to AWS

on:
  push:
    branches:
      - main
      - front-end

jobs:
  deploy:
    name: Build & Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      # ─────────────────────────────────────────────────────────────
      # 🧪 Backend: Install, Test, Build
      # ─────────────────────────────────────────────────────────────

      - name: Install dependencies
        working-directory: src
        run: npm install

      - name: Run tests
        run: npm install && npm test

      - name: Install rimraf globally
        run: npm install -g rimraf

      - name: Build TypeScript
        working-directory: src
        run: npm run build

      - name: Copying dependencies to dist
        run: |
          mkdir -p src/dist/node_modules
          cp -r src/node_modules/* src/dist/node_modules/
          cp -r src/package.json src/dist/package.json

      - name: Build with SAM
        run: sam build

      - name: Deploy with SAM
        run: |
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name serverless-user-api \
            --region eu-central-1 \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --parameter-overrides ParameterKey=JwtSecret,ParameterValue=$JWT_SECRET
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      # ─────────────────────────────────────────────────────────────
      # 🎨 Frontend: Build & Deploy to S3
      # ─────────────────────────────────────────────────────────────

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Inject Vite env variables
        working-directory: frontend
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env
          echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> .env

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Upload to S3
        run: |
          aws s3 sync frontend/dist s3://${{ secrets.FRONTEND_BUCKET_NAME }} --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}