name: Deploy SAM App to AWS

on:
  push:
    branches:
      - main
      - cursor/migrate-repository-to-typescript-a311

jobs:
  deploy:
    name: Build & Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Install dependencies
        run: cd src && npm install && cd ..

      - name: Build TypeScript
        run: cd src && npm run build && cd ..

      - name: Build with SAM
        run: sam build

      - name: Deploy with SAM
        run: |
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name serverless-user-api \
            --region eu-central-1 \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --parameter-overrides ParameterKey=JwtSecret,ParameterValue=$JWT_SECRET
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
